:output:
  Category:
    :options:
      :fields:
        - id
        - menu_id
        - parent_id
        - title
        - level
        - style
        - position
  Restaurant:
    :options:
      :fields:
        - id
        - user_id
        - name
        - telephone
        - website
        - download_code
        - email