:output:
  Category:
    :options:
      :fields:
        - menu_id
        - category_id
        - title
        - level
        - style
        - dishes_id
        - position
  BeveragePage:
    :options:
      :fields:
        - id
        - restaurant_id
        - title
  Restaurant:
    :options:
      :fields:
        - id
        - user_id
        - name
        - telephone
        - website
        - download_code
        - email